# tasks file for ansible-stern
- name: Get latest Release from stern
  shell: curl -Lo /tmp/stern.tar.gz https://github.com/stern/stern/releases/download/$(curl -s https://api.github.com/repos/stern/stern/releases/latest | grep tag_name | cut -d '"' -f 4)/stern_$(curl -s https://api.github.com/repos/stern/stern/releases/latest | grep tag_name | cut -d '"' -f 4| tr -d v)_{{ ansible_system | lower }}_amd64.tar.gz
  args:
    warn: no
  when: ansible_architecture == 'x86_64'
  tags: stern

- name: Unarchive a file
  shell: tar -xvf /tmp/stern.tar.gz -C /usr/local/bin/ stern
  args:
    warn: no
  tags: stern

# - name: Change file ownership, group and permissions
#   ansible.builtin.file:
#     path: /opt/stern/stern
#     owner: root
#     group: root
#     mode: '0755'
#   tags: stern

- name: Verify stern exists
  stat: path=/usr/local/bin/stern
  register: stern_stat
  tags: stern

# - command: stern version
#   register: result_stern
#   failed_when: false
#   changed_when: false
#   tags: stern

# - debug:
#     var: result_stern.stdout
#   tags: stern
